name: testreport
version: 0.2.0
description: >
  This library can be used to process the results of dart tests.
  The goal of this library is to process the data from the `json` output emitted by the dart test runner
  and provide an API to the interpreted test results.

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/TOPdesk/dart-testreport
documentation:

dependencies:
  built_collection: '^1.0.2'

dev_dependencies:
  test: any

environment:
  sdk: '>=1.8.3 <2.0.0'