name: testreport
version: 1.1.0
description: >
  This library can be used to process the results of dart tests.
  It processes the data from the `json` output emitted by the dart test runner
  and provide an API to the interpreted test results.

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/TOPdesk/dart-testreport
documentation:

dependencies:

dev_dependencies:
  test: any
  pedantic: ^1.8.0

environment:
  sdk: '>=2.3.0 <3.0.0'